ALTER TABLE users
ADD COLUMN IF NOT EXISTS password TEXT,
ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'user',
ADD COLUMN IF NOT EXISTS refresh_token TEXT,
ADD COLUMN IF NOT EXISTS otp_verified BOOLEAN DEFAULT false;

ALTER TABLE users ADD CONSTRAINT chk_user_role CHECK (role IN ('user', 'admin'));